### ISSUE TITLE
Any progress in Minsky frame ?

### ISSUE THREAD

**Issue by ponyatov** [ronaldosvieira/cppframes#1]
Do you have any progrress in Minsky frames applications ? 

I'm search in some tutorual on frames application (python preferref), can yoy recommend some intro besides Minsky book itself ?

**Comment by ronaldosvieira** [comment]
Hi :)

I needed a data structure to represent a semantic model and so I came across Minsky's frames in the book **Knowledge representation and reasoning** by Ronald J. Brachman and Hector J. Levesque (chapter 8). Hope you can find it useful.

**Comment by ponyatov** [comment]
Thanks. Huge price for paper, I'll try to find some reduced online version.

**Comment by ronaldosvieira** [comment]
Ok. Best of luck!

**Comment by ponyatov** [comment]
Oops I found some OCR: https://courses.cs.washington.edu/courses/cse574/01wi/readings/brachman-levesque-krr.pdf
